# Control Flow

In [17]:
from __future__ import print_function
import tensorflow as tf
import numpy as np

In [18]:
from datetime import date
date.today()

datetime.date(2018, 4, 27)

In [19]:
author = "kyubyong. https://github.com/Kyubyong/tensorflow-exercises"

In [20]:
tf.__version__

'1.5.0'

In [21]:
np.__version__

'1.14.1'

In [22]:
sess = tf.InteractiveSession()

NOTE on notation
* _x, _y, _z, ...: NumPy 0-d or 1-d arrays
* _X, _Y, _Z, ...: NumPy 2-d or higer dimensional arrays
* x, y, z, ...: 0-d or 1-d tensors
* X, Y, Z, ...: 2-d or higher dimensional tensors

## Control Flow Operations

Q1. Let x and y be random 0-D tensors. Return x + y if x < y and x - y otherwise.

In [23]:
x = tf.random_uniform([])
y = tf.random_uniform([])
out = tf.cond(x < y, lambda: x+y, lambda: x-y)
out.eval()

1.86504

Q2. Let x and y be 0-D int32 tensors randomly selected from 0 to 5. Return x + y 2 if x < y, x - y elif x > y, 0 otherwise.

In [24]:
x = tf.random_uniform([] ,0 ,5)
y = tf.random_uniform([] ,0 ,5)

tf.cond(x<y, lambda: x + y, lambda: 0.0).eval()

4.906268

Q3. Let X be a tensor [[-1, -2, -3], [0, 1, 2]] and Y be a tensor of zeros with the same shape as X. Return a boolean tensor that yields True if X equals Y elementwise.

In [26]:
_X = np.array([[-1, -2, -3], [0, 1, 2]])
x = tf.constant(_X)
y = tf.zeros_like(x)
tf.equal(x,y).eval()

array([[False, False, False],
       [ True, False, False]])

## Logical Operators

Q4. Given x and y below, return the truth value x AND/OR/XOR y element-wise.

In [30]:
x = tf.constant([True, False, False], tf.bool)
y = tf.constant([True, True, False], tf.bool)

print(tf.logical_and(x,y).eval())
print(tf.logical_or(x,y).eval())
print(tf.logical_xor(x,y).eval())

[ True False False]
[ True  True False]
[False  True False]


Q5. Given x, return the truth value of NOT x element-wise.

In [32]:
x = tf.constant([True, False, False], tf.bool)

tf.logical_not(x).eval()

array([False,  True,  True])

## Comparison Operators

Q6. Let X be a tensor [[-1, -2, -3], [0, 1, 2]] and Y be a tensor of zeros with the same shape as x. Return a boolean tensor that yields True if X does not equal Y elementwise.

In [33]:
_x = np.array([[-1, -2, -3], [0, 1, 2]])
X = tf.constant(_x)
Y = tf.zeros_like(X)
tf.not_equal(X, Y).eval()

array([[ True,  True,  True],
       [False,  True,  True]])

Q7. Let X be a tensor [[-1, -2, -3], [0, 1, 2]] and Y be a tensor of zeros with the same shape as X. Return a boolean tensor that yields True if X is greater than or equal to Y elementwise.

In [36]:
_x = np.array([[-1, -2, -3], [0, 1, 2]])
X = tf.constant(_x)
Y = tf.zeros_like(X)

tf.greater_equal(X,Y).eval()

array([[False, False, False],
       [ True,  True,  True]])

Q8. Let X be a tensor [[1, 2], [3, 4]], Y be a tensor [[5, 6], [7, 8]], and Z be a boolean tensor [[True, False], [False, True]]. Create a 2*2 tensor such that each element corresponds to X if Z is True, otherise Y.

In [37]:
_x = np.array([[1,2],[3,4]])
_y = np.array([[5,6],[7,8]])
Z = tf.constant([[True, False], [False, True]], tf.bool)
out = tf.where(Z, X, Y)
print(out.eval())


ValueError: Dimension 1 in both shapes must be equal, but are 3 and 2. Shapes are [2,3] and [2,2]. for 'Select' (op: 'Select') with input shapes: [2,2], [2,3], [2,3].