# Math Part 2

In [1]:
from __future__ import print_function
import tensorflow as tf
import numpy as np

In [2]:
from datetime import date
date.today()

datetime.date(2018, 4, 26)

In [3]:
author = "kyubyong. https://github.com/Kyubyong/tensorflow-exercises"

In [4]:
tf.__version__

'1.5.0'

In [5]:
np.__version__

'1.14.1'

In [6]:
sess = tf.InteractiveSession()

NOTE on notation
* _x, _y, _z, ...: NumPy 0-d or 1-d arrays
* _X, _Y, _Z, ...: NumPy 2-d or higer dimensional arrays
* x, y, z, ...: 0-d or 1-d tensors
* X, Y, Z, ...: 2-d or higher dimensional tensors

## Matrix Math Functions

Q1. Create a diagonal tensor with the diagonal values of x.

In [9]:
_x = np.array([1, 2, 3, 4])
x = tf.convert_to_tensor(_x)

tf.diag(x).eval()

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

Q2. Extract the diagonal of X.

In [11]:
_X = np.array(
[[1, 0, 0, 0],
 [0, 2, 0, 0],
 [0, 0, 3, 0],
 [0, 0, 0, 4]])
X = tf.convert_to_tensor(_X)

tf.diag_part(X).eval()

array([1, 2, 3, 4])

Q3. Permutate the dimensions of x such that the new tensor has shape (3, 4, 2).

In [20]:
_X = np.random.rand(2,3,4)
X = tf.convert_to_tensor(_X)

out = tf.transpose(X, [1, 2, 0])

print("X")
print(_X)
print("Transpose")
print(out.eval())

X
[[[0.47965825 0.01339785 0.49738173 0.41459205]
  [0.89447506 0.26243401 0.91107874 0.38525125]
  [0.50243375 0.72586606 0.80011494 0.95435065]]

 [[0.65931342 0.42383856 0.2604992  0.71747069]
  [0.9336796  0.74248048 0.04379884 0.40575994]
  [0.04643247 0.10325821 0.51330666 0.88882054]]]
Transpose
[[[0.47965825 0.65931342]
  [0.01339785 0.42383856]
  [0.49738173 0.2604992 ]
  [0.41459205 0.71747069]]

 [[0.89447506 0.9336796 ]
  [0.26243401 0.74248048]
  [0.91107874 0.04379884]
  [0.38525125 0.40575994]]

 [[0.50243375 0.04643247]
  [0.72586606 0.10325821]
  [0.80011494 0.51330666]
  [0.95435065 0.88882054]]]


Q4. Construct a 3 by 3 identity matrix.

In [27]:
tf.eye(3).eval()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

Q5. Predict the result of this.

In [28]:
_X = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
X = tf.convert_to_tensor(_X)

diagonal_tensor = tf.matrix_diag(X)
diagonal_part = tf.matrix_diag_part(diagonal_tensor)

print("diagonal_tensor =\n", diagonal_tensor.eval())
print("diagonal_part =\n", diagonal_part.eval())


diagonal_tensor =
 [[[1 0 0 0]
  [0 2 0 0]
  [0 0 3 0]
  [0 0 0 4]]

 [[5 0 0 0]
  [0 6 0 0]
  [0 0 7 0]
  [0 0 0 8]]]
diagonal_part =
 [[1 2 3 4]
 [5 6 7 8]]


Q6. Transpose the last two dimensions of X.

In [32]:
_X= np.random.rand(1, 2, 3, 4)
X = tf.convert_to_tensor(_X)

print("X")
print(_X)
print("transpose")
print(tf.transpose(X,[0,1,3,2]).eval())

X
[[[[0.14704674 0.12420213 0.91406271 0.72998899]
   [0.08306211 0.08708485 0.69543132 0.47772608]
   [0.94154137 0.049686   0.35410933 0.0689639 ]]

  [[0.2106135  0.81850191 0.66936526 0.76392977]
   [0.01428204 0.45530336 0.16963177 0.61237312]
   [0.87727663 0.15967411 0.40825359 0.64097417]]]]
transpose
[[[[0.14704674 0.08306211 0.94154137]
   [0.12420213 0.08708485 0.049686  ]
   [0.91406271 0.69543132 0.35410933]
   [0.72998899 0.47772608 0.0689639 ]]

  [[0.2106135  0.01428204 0.87727663]
   [0.81850191 0.45530336 0.15967411]
   [0.66936526 0.16963177 0.40825359]
   [0.76392977 0.61237312 0.64097417]]]]


Q7. Multiply X by Y.

In [45]:
_X = np.array([[1, 2, 3], [4, 5, 6]])
_Y = np.array([[1, 1], [2, 2], [3, 3]])
X = tf.convert_to_tensor(_X,dtype=np.int32)
Y = tf.convert_to_tensor(_Y,dtype=np.int32)

out = tf.matmul(X, Y)
print(out.eval())

_out = np.dot(_X, _Y)
assert np.array_equal(out.eval(), _out)

[[14 14]
 [32 32]]


Q8. Multiply X and Y. The first axis represents batches.

In [14]:
_X = np.arange(1, 13, dtype=np.int32).reshape((2, 2, 3))
_Y = np.arange(13, 25, dtype=np.int32).reshape((2, 3, 2))
X = tf.convert_to_tensor(_X)
Y = tf.convert_to_tensor(_Y)




[[[ 94 100]
  [229 244]]

 [[508 532]
  [697 730]]]


In [47]:
_X = np.arange(1, 13, dtype=np.int32).reshape((2, 2, 3))
_Y = np.arange(13, 25, dtype=np.int32).reshape((2, 3, 2))
X = tf.convert_to_tensor(_X)
Y = tf.convert_to_tensor(_Y)

print(_X)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [48]:
print(_Y)

[[[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]]


In [51]:
tf.matmul(X,Y).eval()

array([[[ 94, 100],
        [229, 244]],

       [[508, 532],
        [697, 730]]], dtype=int32)

Q9. Compute the determinant of X.

In [53]:
_X = np.arange(1, 5, dtype=np.float32).reshape((2, 2))
X = tf.convert_to_tensor(_X)

tf.matrix_determinant(X).eval()

-2.0

Q10. Compute the inverse of X.


In [54]:
_X = np.arange(1, 5, dtype=np.float64).reshape((2, 2))
X = tf.convert_to_tensor(_X)

tf.matrix_inverse(X).eval()

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

Q11. Get the lower-trianglular in the Cholesky decomposition of X.

In [55]:
_X = np.array([[4, 12, -16], [12, 37, -43], [-16, -43, 98]], np.float32)
X = tf.convert_to_tensor(_X)

tf.cholesky(X).eval()

array([[ 2.,  0.,  0.],
       [ 6.,  1.,  0.],
       [-8.,  5.,  3.]], dtype=float32)

Q12. Compute the eigenvalues and eigenvectors of X.

In [62]:
_X = np.diag((1, 2, 3))
X = tf.convert_to_tensor(_X, tf.float32)

e= tf.linalg.eigh(X)
print(e[0].eval())
print(e[1].eval())

[1. 2. 3.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Q13. Compute the singular values of X.

In [65]:
_X = np.array(
[[1, 0, 0, 0, 2], 
 [0, 0, 3, 0, 0], 
 [0, 0, 0, 0, 0], 
 [0, 2, 0, 0, 0]], dtype=np.float32)
X = tf.convert_to_tensor(_X)

tf.svd(X)[0].eval()

array([3.      , 2.236068, 2.      , 0.      ], dtype=float32)

## Reduction

Q14. Predict the results of these.

In [66]:
_X = np.array(
    [[1, 2, 3, 4],
     [5, 6, 7, 8]])
X = tf.convert_to_tensor(_X)

outs = [tf.reduce_sum(X),
        tf.reduce_sum(X, axis=0),
        tf.reduce_sum(X, axis=1, keep_dims=True),
        "",
        tf.reduce_prod(X),
        tf.reduce_prod(X, axis=0),
        tf.reduce_prod(X, axis=1, keep_dims=True),
        "",
        tf.reduce_min(X),
        tf.reduce_min(X, axis=0),
        tf.reduce_min(X, axis=1, keep_dims=True),
        "",
        tf.reduce_max(X),
        tf.reduce_max(X, axis=0),
        tf.reduce_max(X, axis=1, keep_dims=True),
        "",
        tf.reduce_mean(X),
        tf.reduce_mean(X, axis=0),
        tf.reduce_mean(X, axis=1, keep_dims=True)
           ]
           
for out in outs:
    if out == "":
        print()
    else:
        print("->", out.eval())
# If you remove the common suffix "reduce_", you will get the same 
# result in numpy.

Instructions for updating:
keep_dims is deprecated, use keepdims instead
Instructions for updating:
keep_dims is deprecated, use keepdims instead
Instructions for updating:
keep_dims is deprecated, use keepdims instead
Instructions for updating:
keep_dims is deprecated, use keepdims instead
Instructions for updating:
keep_dims is deprecated, use keepdims instead
-> 36
-> [ 6  8 10 12]
-> [[10]
 [26]]

-> 40320
-> [ 5 12 21 32]
-> [[  24]
 [1680]]

-> 1
-> [1 2 3 4]
-> [[1]
 [5]]

-> 8
-> [5 6 7 8]
-> [[4]
 [8]]

-> 4
-> [3 4 5 6]
-> [[2]
 [6]]


Q15. Predict the results of these.

In [68]:
_X = np.array([[True, True],
              [False, False]], np.bool)
X = tf.convert_to_tensor(_X)

outs = [tf.reduce_all(X),
        tf.reduce_all(X, axis=0),
        tf.reduce_all(X, axis=1, keep_dims=True),
        "",
        tf.reduce_any(X),
        tf.reduce_any(X, axis=0),
        tf.reduce_any(X, axis=1, keep_dims=True),
        ]

# for out in outs:
if out == "":
    print()
else:
    print("->", out.eval())

# If you remove the common suffix "reduce_", you will get the same 
# result in numpy.

Instructions for updating:
keep_dims is deprecated, use keepdims instead
Instructions for updating:
keep_dims is deprecated, use keepdims instead
-> [[2]
 [6]]


Q16. Predict the results of these.

In [69]:
_X = np.array([[0, 1, 0],
              [1, 1, 0]])
X = tf.convert_to_tensor(_X)

outs = [tf.count_nonzero(X),
        tf.count_nonzero(X, axis=0),
        tf.count_nonzero(X, axis=1, keep_dims=True),
        ]

for out in outs:
    print("->", out.eval())

# tf.count_nonzero == np.count_nonzero

Instructions for updating:
keep_dims is deprecated, use keepdims instead
-> 3
-> [1 2 0]
-> [[1]
 [2]]


Q17. Complete the einsum function that would yield the same result as the given function.

In [73]:
_X = np.arange(1, 7).reshape((2, 3))
_Y = np.arange(1, 7).reshape((3, 2))

X = tf.convert_to_tensor(_X, dtype=np.int32)
Y = tf.convert_to_tensor(_Y, dtype=np.int32)


In [74]:

# Matrix multiplication
out1 = tf.matmul(X, Y)
out1_ = tf.einsum('ij,jk->ik', X, Y)
assert np.allclose(out1.eval(), out1_.eval())
