# Math Part 3

In [1]:
from __future__ import print_function
import tensorflow as tf
import numpy as np

In [2]:
from datetime import date
date.today()

datetime.date(2018, 4, 26)

In [3]:
author = "kyubyong. https://github.com/Kyubyong/tensorflow-exercises"

In [4]:
tf.__version__

'1.5.0'

In [5]:
np.__version__

'1.14.1'

In [6]:
sess = tf.InteractiveSession()

NOTE on notation
* _x, _y, _z, ...: NumPy 0-d or 1-d arrays
* _X, _Y, _Z, ...: NumPy 2-d or higer dimensional arrays
* x, y, z, ...: 0-d or 1-d tensors
* X, Y, Z, ...: 2-d or higher dimensional tensors

## Scan

Q1. Compute the cumulative sum of X along the second axis.

In [8]:
_X = np.array([[1,2,3], [4,5,6]])
X = tf.convert_to_tensor(_X)

tf.cumsum(X).eval()

array([[1, 2, 3],
       [5, 7, 9]])

Q2. Compute the cumulative product of X along the second axis.

In [9]:
_X = np.array([[1,2,3], [4,5,6]])
X = tf.convert_to_tensor(_X)

tf.cumprod(X).eval()

array([[ 1,  2,  3],
       [ 4, 10, 18]])

## Segmentation

Q3. Compute the sum along the first two elements and 
the last two elements of X separately.

In [15]:
_X = np.array(
    [[1,2,3,4], 
     [-1,-2,-3,-4], 
     [-10,-20,-30,-40],
     [10,20,30,40]])
X = tf.convert_to_tensor(_X)

tf.segment_sum(X,[0,0,1,1]).eval()

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

Q4. Compute the product along the first two elements and the last two elements of X separately.

In [17]:
_X = np.array(
    [[1,2,3,4], 
     [1,1/2,1/3,1/4], 
     [1,2,3,4],
     [-1,-1,-1,-1]])
X = tf.convert_to_tensor(_X)

tf.segment_prod(X,[0,0,1,1]).eval()

array([[ 1.,  1.,  1.,  1.],
       [-1., -2., -3., -4.]])

Q5. Compute the minimum along the first two elements and the last two elements of X separately.

In [19]:
_X = np.array(
    [[1,4,5,7], 
     [2,3,6,8], 
     [1,2,3,4],
     [-1,-2,-3,-4]])
X = tf.convert_to_tensor(_X)

tf.segment_min(X,[0,0,1,1]).eval()


array([[ 1,  3,  5,  7],
       [-1, -2, -3, -4]])

Q6. Compute the maximum along the first two elements and the last two elements of X separately.

In [20]:
_X = np.array(
    [[1,4,5,7], 
     [2,3,6,8], 
     [1,2,3,4],
     [-1,-2,-3,-4]])
X = tf.convert_to_tensor(_X)

tf.segment_max(X,[0,0,1,1]).eval()

array([[2, 4, 6, 8],
       [1, 2, 3, 4]])

Q7. Compute the mean along the first two elements and the last two elements of X separately.

In [21]:
_X = np.array(
    [[1,2,3,4], 
     [5,6,7,8], 
     [-1,-2,-3,-4],
     [-5,-6,-7,-8]])
X = tf.convert_to_tensor(_X)

tf.segment_mean(X,[0,0,1,1]).eval()

array([[ 3,  4,  5,  6],
       [-3, -4, -5, -6]])

Q8. Compute the sum along the second and fourth and 
the first and third elements of X separately in the order.

In [25]:
_X = np.array(
    [[1,2,3,4], 
     [-1,-2,-3,-4], 
     [-10,-20,-30,-40],
     [10,20,30,40]])
X = tf.convert_to_tensor(_X)

tf.unsorted_segment_sum(X,[0,1,0,1],2).eval()

array([[ -9, -18, -27, -36],
       [  9,  18,  27,  36]])

In [26]:
help(tf.unsorted_segment_sum)

Help on function unsorted_segment_sum in module tensorflow.python.ops.gen_math_ops:

unsorted_segment_sum(data, segment_ids, num_segments, name=None)
    Computes the sum along segments of a tensor.
    
    Read @{$math_ops#segmentation$the section on segmentation} for an explanation of
    segments.
    
    Computes a tensor such that
    `(output[i] = sum_{j...} data[j...]` where the sum is over tuples `j...` such
    that `segment_ids[j...] == i`.  Unlike `SegmentSum`, `segment_ids`
    need not be sorted and need not cover all values in the full
    range of valid values.
    
    If the sum is empty for a given segment ID `i`, `output[i] = 0`.
    If the given segment ID `i` is negative, the value is dropped and will not be
    added to the sum of the segment.
    
    `num_segments` should equal the number of distinct segment IDs.
    
    <div style="width:70%; margin:auto; margin-bottom:10px; margin-top:20px;">
    <img style="width:100%" src="https://www.tensorflow.org/image

## Sequence Comparison and Indexing 


Q9. Get the indices of maximum and minimum values of X along the second axis.


In [33]:
_X = np.random.permutation(10).reshape((2, 5))
print("_X =", _X)
X = tf.convert_to_tensor(_X)

tf.argmax(X,axis=1).eval()
tf.argmin(X,axis=1).eval()

_X = [[4 1 7 3 9]
 [0 6 2 8 5]]


array([1, 0])

Q10. Find the unique elements of x that are not present in y.

In [43]:
_x = np.array([0, 1, 2, 5, 0])
_y = np.array([0, 1, 4])
x = tf.convert_to_tensor(_x)
y = tf.convert_to_tensor(_y)

out = tf.setdiff1d(x, y)[0]

out.eval()

array([2, 5])

Q11. Return the elements of X, if X < 4, otherwise X*10.

In [44]:
_X = np.arange(1, 10).reshape(3, 3)
X = tf.convert_to_tensor(_X)

out = tf.where(X < 4, X, X*10)
out.eval()

array([[ 1,  2,  3],
       [40, 50, 60],
       [70, 80, 90]])

Q12. Get unique elements and their indices from x.

In [45]:
_x = np.array([1, 2, 6, 4, 2, 3, 2])
x = tf.convert_to_tensor(_x)

out, indices = tf.unique(x)
indices.eval()

array([0, 1, 2, 3, 1, 4, 1], dtype=int32)

Q13. Compute the edit distance between hypothesis and truth.

In [49]:
# Check the documentation on tf.SparseTensor if you are not
# comfortable with sparse tensor.
hypothesis = tf.SparseTensor(
    [[0, 0],[0, 1],[0, 2],[0, 4]],
    ["a", "b", "c", "a"],
    (1, 5)) 
# Note that this is equivalent to the dense tensor.
# [["a", "b", "c", 0, "a"]]

truth = tf.SparseTensor(
    [[0, 0],[0, 2],[0, 4]],
    ["a", "c", "b"],
    (1, 6))
# This is equivalent to the dense tensor.
# [["a", 0, "c", 0, "b", 0]]

tf.edit_distance(hypothesis,truth, normalize=True).eval()
tf.edit_distance(hypothesis,truth, normalize=False).eval()

array([2.], dtype=float32)